root: true
env:
  node: true
parserOptions:
  ecmaVersion: 2021
extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:mdx/recommended
  - prettier
rules:
  react/jsx-uses-react: "off"
  react/prop-types: "off"
  react/react-in-jsx-scope: "off"
  react/no-unknown-property: "off"
overrides:
  - files: "src/public/**/*.js"
    env:
      node: false
      browser: true
  - files: "src/**/*.mdx"
    globals:
      props: readonly
settings:
  react:
    version: "16.0"
