name: CI
on:
  pull_request_target:
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: yarn
      - run: yarn install --check-files --frozen-lockfile --non-interactive
      - run: yarn lint
      - id: format
        run: |
          yarn format
          echo "status=$(git status --porcelain)" >> $GITHUB_OUTPUT
      - if: steps.format.outputs.status != ''
        run: |
          git -c "user.name=github-actions[bot]" -c "user.email=github-actions[bot]@users.noreply.github.com" commit -a -m "bot: format"
          git push origin HEAD
