name: CI
on:
  pull_request:
    types: [opened, reopened, synchronize]
jobs:
  ci:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: yarn
      - run: yarn install --check-files --frozen-lockfile --non-interactive
      - run: yarn lint
      - run: yarn format
      - id: diff
        run: echo "RESULT=$(git diff --shortstat)" >> $GITHUB_OUTPUT
      - if: steps.diff.outputs.RESULT != ''
        run: |
          git -c "user.name=${{ github.actor }}" -c "user.email=${{ github.actor }}@users.noreply.github.com" commit -a -m "bot: format"
          git push origin HEAD
