name: Lint
on:
  pull_request:
    types: [opened, reopened, synchronize]
jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: yarn
      - uses: reviewdog/action-setup@v1
      - run: yarn install --check-files --frozen-lockfile --non-interactive
      - run: yarn --silent lint:rdjson | reviewdog -f=rdjson -reporter=github-pr-review -fail-on-error=true
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ github.token }}
